name: Sonorium
version: "1.3.2"
slug: sonorium
description: Ambient soundscape mixer with crossfade looping for Home Assistant
url: https://github.com/synssins/sonorium

arch:
  - aarch64
  - amd64

init: false
homeassistant_api: true
audio: false

services:
  - mqtt:need

map:
  - media:rw
  - config:rw

ports:
  8080/tcp: 8007
ports_description:
  8080/tcp: "Sonorium Web UI and streaming API"

panel_icon: mdi:waveform
webui: http://[HOST]:[PORT:8080]/

options:
  sonorium__stream_url: "http://homeassistant.local:8007"
  sonorium__path_audio: "/media/sonorium"

schema:
  sonorium__stream_url: str
  sonorium__path_audio: str

startup: application
stage: experimental
